project:
  type: website
  output-dir: _site
 
  
website:
  page-navigation: true # não funciona
  image: RStudioLogo.png # não funciona
  reader-mode: true # funciona
  google-analytics: "G-S1L73VGCG5"
  title: "Vivificando Conteúdos ao Ensino Médio" # omite-se o título pra não duplicar nome na aba
  favicon: avatar.png # ícone da aba da página
  
  sidebar:
    - contents:
      - section: "Treinamento"
        contents:
          - text: "Saudações"
            href: index.qmd
          - questoes.qmd
          - ferramentas.qmd
          - jmolPart.qmd
          - jmol.qmd
          - textoXmouse.qmd
          - comandosJmol.qmd
         # - selecao.qmd
         # - animacao.qmd
          - RPart.qmd
          - rstudioCloud.qmd
          - basicaoR.qmd
          - graphics.qmd
          - pacotes.qmd
          - animationPlots.qmd
          - manipulate.qmd
          - ggplot2.qmd
          - gganimate.qmd
          - plotly.qmd
          - leaflet.qmd
      - contato.qmd
            
            
  navbar:
    search: true
    logo: avatar.png # logo ao lado esquerdo da Home
    background: primary # cor de fundo
    tools:  # ícones específico
      # - icon: twitter
      #   href: https://twitter.com
      - icon: bank
        menu:
          - text: UNIFAL-MG
            href:  https://www.unifal-mg.edu.br/portal/index/
          - text: Depto. Bioquímica
            href:  https://www.unifal-mg.edu.br/dbq/
  
    left:
      #- href: index.qmd
       # text: Home
      - text: "Moléculas Voadoras, Gráficos e Mapas Interativos"
        menu:
          - index.qmd
         #  - questoes.qmd
         #  - ferramentas.qmd
         #  - jmolPart.qmd
         #  - jmol.qmd
         #  - textoXmouse.qmd
         #  - comandosJmol.qmd
         #  - selecao.qmd
         #  - animacao.qmd
         #  - RPart.qmd
         #  - rstudioCloud.qmd
         #  - basicaoR.qmd
         #  - graphics.qmd
         #  - pacotes.qmd
         #  - animationPlots.qmd
         #  - manipulate.qmd
         #  - ggplot2.qmd
         #  - gganimate.qmd
         #  - plotly.qmd
         #  - leaflet.qmd
      - contato.qmd
      
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: source

