---
title: "Tudo junto agora - o pacote `flexdashboards`"
---

|       Até agora vimos algumas características de bibiliotecas gráficas e interativas do `R`, e voltadas à visulização, simulação, e animação de conteúdos. Cada biblioteca (ou *package*) possui uma sintaxe particular, e um produto de renderização específico. 


|       Agora imagine a possibilidade de unir alguns resultados de uma análise, de gráficos interativos, e/ou simulações de diferentes bibliotecas em uma mesma página, como um **painel** (*dashboard*, por vezes um *relatório dinâmico*). Isso é bem comum hoje em dia, incluindo paineis de algumas *big techs*, como o [Looker Studio](https://lookerstudio.google.com/u/0/navigation/reporting) do *Google* e o [Power Bi](https://learn.microsoft.com/pt-br/power-bi/create-reports/service-dashboards) da *Microsoft*. 


|       Para o `R` também existem alguns pacotes que permitem a criação de paineis, e mesmo uma moldura completa de trabalho (*framework*) para o desenvolvimento de aplicativos *web* completos, denominada [shiny](https://shiny.posit.co/). No presente capítulo vamos nos ater a um pacote mais intuitivo para a criação de paineis, o `flexdashboards`.



## Referência do pacote:

* [Geral](https://cran.r-project.org/web/packages/flexdashboard/index.html)
* [Manual](https://cran.r-project.org/web/packages/flexdashboard/flexdashboard.pdf)
* [Tutorial](https://rstudio.github.io/flexdashboard/articles/examples.html) 