---
title: "Algumas questões prévias"
---

## De que se trata esse material ?

|       Bom, como diz o título, de *vivificar* imagens e relações numéricas encontrados em livros-texto. Em palavras mais abstratas...da tentativa de se oferecer algumas ferramentas para compor objetos didáticos para *qualquer área do Ensino Médio*.

|       Agora, de modo mais específico, de instrumentalizar professores ao uso de dois programas básicos de computador, um para *visualização de moléculas em 3D*, e outro para *vivificar* algumas relações estáticas encontradas em livros-texto por *animações, interatividade, e simulações*.

## Qual a vantagem em se familiarizar com esses programas ?

|       Também em módicos termos, para oferecer aos alunos uma visão mais *paupável e amigável* de conteúdos trazidos de livros-texto do nível educacional da proposta.

## Como alunos do ensino médio podem beneficiar-se da oferta das ferramentas que serão tratadas aqui ?

|       Isto tem muito a ver com o conceito de *letramento visual (visual literacy)* e também com *letramento científico*. Em síntese, os livros-texto oferecem formas distintas de apresentação de conteúdos, e que exigem do estudante diferentes **níveis de abstração**, como o *simbólico* (fórmula estrutural, equação), *esquemático* (fluxogramas, geovisualização), *gráfico* (relação entre variáveis), *realístico* (resultado experimental), e de *cartoon* (estrutura molecular).

|       Assim, pretende-se oferecer uma ferramenta para auxiliar na abstração *de cartoon*, e outra para o *simbólico*, *esquemático*, *gráfico*, e de análise de dados presente na abstração *realística*. Essa segunda ferramenta permitirá acessar o conteúdo de livros-texto por animações e simulações.

|       Na *prática imediata e de curto prazo*, essas ferramentas poderão possibilitar um menor nível de abstração para alguns conteúdos encontrados em *livros-texto do Ensino Médio*, por exemplo:

-   permitindo a visualização de uma molécula em 3D, sua rotação, tamanho, estudo estrutural e químico, funções orgânicas, relações de estrutura e função, e animações.
-   permitindo a elaboração de gráficos animados a partir de equações, visualização interativa de gráficos, e simulações.

## E quais são essas ferramentas ?

|       Para a *visualização de moléculas em 3D* será empregado o programa **Jmol**, e para os demais mencionados o programa **R** com sua interface gráfica **RStudio**. São programas gratuitos para instalação em computador de mesa ou notebook, embora também acessáveis por navegador de internete, e nesse caso, sem necessidade de instalação. Essa versão em nuvem foi a escolhida para este *Curso* aos dois programas.

<!-- ## Se este material envolve o uso de livros-texto, qual bibliografia será utilizada ? -->

<!-- |       Será utilizado algum conteúdo geral presente no [Material de Apoio Pedagógico para Aprendizagens - MAPA](https://seliga.educacao.mg.gov.br/cardenos-mapa/ensino-m%C3%A9dio-2024) para habilidades previstas no *Currículo Referência de Minas Gerais*, e pertinente principalmente à *Ciências da Natureza, Matemática, e Suas Tecnologias*. Também será utilizado alguns bancos de dados digitais de interesse técnico-científico. -->

## Além dos conteúdos específicos com algum potencial para melhorar o aprendizado do estudante, há outra vantagem ao usuário no aprendizado dos programas ?

|       Diversas. De início, a familiarização com **linguagens de programação**. O *Jmol* é mais fechado, e trabalha somente com a compilação de códigos para modelos atômicos. O que já é muito bom para se visualizar a imensidade de moléculas presentes em livros-texto. Já o *R* é outra história.


|       O *R* permite uma infinidade de ações, quer voltadas à pesquisa ou ao ensino. É utilizado por diversas Universidades ao redor do mundo, bem como por diversas empresas de porte (ex: Google, Facebook, LinkedIn, Twitter, Bank of America, Lenovo, Bing). Embora tenha sido originalmente desenvolvido para análise de dados, possui hoje mais de 20 mil pacotes adicionais.


|       Essa expansibilidade permite, por exemplo, recursos de matemática, estatística, gráficos e tabelas avançados, animações e simulações, análise de imagem e de texto, criação musical e artística, ciência de dados, inteligência artificial, comunicação com placas microcontroladores (ex: *Arduino*), internete das coias (*IoT*), criação de *blogs*, de livros e mesmo de  *websites*, tal como este, usado para produzir produzir o material do *Curso*.


## E o tal *Ensino Reprodutível*, de que se trata ?


|       *Ensino Reprodutível (ER)* uma metodologia ativa em ensino-aprendizagem ainda em formação, e que mistura trechos de algoritmos com conteúdos temáticos, ambos editáveis num simples bloco de notas. Na prática, o *ER* envolve aplicar códigos escritos em um programa específico para a produção de um objeto didático, incluindo aí um modelo molecular, um gráfico, uma tabela, uma mídia, um texto formatado com saída em DOCX, PDF ou EPUB, uma animação, e/ou uma simulação, dentre vários.


|       Dessa forma é possível imaginar que um aprendiz agregue valor a seu aprendizado ao 1) repetir a execução do código num programa específico, 2) alterar algum trecho do código para observar um resultado diferente, ou mesmo 3) criar um novo código buscando outro produto final. Nesse caso, a *reprodutibiidade* está centrada na criação/modificação do objeto didático, e que pode ser *realizada por qualquer pessoa que tenha o programa e o código*.
